services:
  redis:
    image: redis

  backend:
    build: ../../example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  web:
    build: ../../example-frontend
    ports:
      - 3000:5000
    depends_on:
      - backend
