services:
  db:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database:/var/lib/postgresql/data

  redis:
    image: redis

  backend:
    build: ../../example-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=secret
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis

  web:
    build: ../../example-frontend
    ports:
      - 3000:5000
    depends_on:
      - backend

  reverse-proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - web
