name: Publish DevOps with Docker - Express App

on:
  push:
    branches:
      - main
    paths:
      - devops-with-docker/part-3/express-app/**

jobs:
  publish-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:devops-with-docker/part-3/express-app"
          push: true
          tags: thomcleary/devopswithdocker-express-app:latest
